name: Build crDroid for a52sxq

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEVICE: a52sxq
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Checkout ROM builder repository
        uses: actions/checkout@v3

      - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

      - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
        
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses6 libncurses-dev libsdl1.2-dev libssl-dev libwxgtk3.2-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python-is-python3

      - name: Install repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=~/bin:$PATH" >> $GITHUB_ENV
          
      - name: Initialize crDroid repo
        run: |
          mkdir crdroid && cd crdroid
          repo init --depth=1 -u https://github.com/crdroidandroid/android.git -b 15.0 --git-lfs


      - name: Clone local_manifests
        run: |
          cd crdroid
          git clone https://github.com/anhdat1024/local_manifests.git -b crDroid-15.0 .repo/local_manifests

      - name: Sync sources
        run: |
          cd crdroid
          repo sync -j7 --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune

      - name: Clean previous builds and setup environment
        run: |
          cd crdroid
          rm -rf out
          source build/envsetup.sh
          lunch lineage_${DEVICE}-bp1a-userdebug
          make clean

      - name: Start building
        run: |
          cd crdroid
          source build/envsetup.sh
          lunch lineage_${DEVICE}-bp1a-userdebug
          mka bacon -j$(nproc --all)

      - name: Find crDroid ROM zip file
        id: get_rom_info
        run: |
          ZIP_FILE=$(ls crdroid/out/target/product/${{ env.DEVICE }}/crDroidAndroid-*.zip | head -n 1)
          ZIP_NAME=$(basename "$ZIP_FILE")
          VERSION_TAG="${ZIP_NAME%.zip}"

          echo "zip_file=$ZIP_FILE" >> $GITHUB_OUTPUT
          echo "version=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_rom_info.outputs.version }}
          name: crDroid ${{ steps.get_rom_info.outputs.version }}
          body: |
            crDroid build for device: ${{ env.DEVICE }}
            Built with GitHub Actions
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Upload ROM to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_rom_info.outputs.version }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          files: ${{ steps.get_rom_info.outputs.zip_file }}
